In [1]:
import numpy as np
import pandas as pd

In [2]:
#make data frame from csv file
data_flight = pd.read_csv (r'C:\Users\ZELIEVES\Downloads\United State Domestic Flights.csv')
data_flight [['flight_date','unique_carrier','flight_num','origin','dest','arr_delay','cancelled','distance','carrier_delay','weather_delay','late_aircraft_delay','nas_delay','security_delay','actual_elapsed_time']]

,flight_date,unique_carrier,flight_num,origin,dest,arr_delay,cancelled,distance,carrier_delay,weather_delay,late_aircraft_delay,nas_delay,security_delay,actual_elapsed_time
0,2015-01-02 00:00:00,AA,1.0,JFK,LAX,-19.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,381.0
1,2015-01-03 00:00:00,AA,1.0,JFK,LAX,-39.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,358.0
2,2015-01-04 00:00:00,AA,1.0,JFK,LAX,-12.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,385.0
3,2015-01-05 00:00:00,AA,1.0,JFK,LAX,-8.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,389.0
4,2015-01-06 00:00:00,AA,1.0,JFK,LAX,25.0,0.0,2475.0,0.0,0.0,0.0,25.0,0.0,424.0
5,2015-01-07 00:00:00,AA,1.0,JFK,LAX,-14.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,382.0
6,2015-01-08 00:00:00,AA,1.0,JFK,LAX,-37.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,362.0
7,2015-01-09 00:00:00,AA,1.0,JFK,LAX,6.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,400.0
8,2015-01-10 00:00:00,AA,1.0,JFK,LAX,0.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,392.0
9,2015-01-11 00:00:00,AA,1.0,JFK,LAX,-36.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,365.0
10,2015-01-12 00:00:00,AA,1.0,JFK,LAX,-5.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,397.0
11,2015-01-13 00:00:00,AA,1.0,JFK,LAX,-40.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,361.0
12,2015-01-14 00:00:00,AA,1.0,JFK,LAX,-69.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,330.0
13,2015-01-02 00:00:00,AA,2.0,LAX,JFK,-8.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,333.0
14,2015-01-03 00:00:00,AA,2.0,LAX,JFK,24.0,0.0,2475.0,22.0,0.0,0.0,2.0,0.0,337.0
15,2015-01-04 00:00:00,AA,2.0,LAX,JFK,150.0,0.0,2475.0,0.0,0.0,105.0,45.0,0.0,324.0
16,2015-01-05 00:00:00,AA,2.0,LAX,JFK,-15.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,328.0
17,2015-01-06 00:00:00,AA,2.0,LAX,JFK,-18.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,313.0
18,2015-01-07 00:00:00,AA,2.0,LAX,JFK,-19.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,320.0
19,2015-01-08 00:00:00,AA,2.0,LAX,JFK,-20.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,316.0
20,2015-01-09 00:00:00,AA,2.0,LAX,JFK,-18.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,319.0
21,2015-01-10 00:00:00,AA,2.0,LAX,JFK,-7.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,324.0
22,2015-01-11 00:00:00,AA,2.0,LAX,JFK,-6.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,330.0
23,2015-01-12 00:00:00,AA,2.0,LAX,JFK,9.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,338.0
24,2015-01-13 00:00:00,AA,2.0,LAX,JFK,-9.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,323.0
25,2015-01-14 00:00:00,AA,2.0,LAX,JFK,-7.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,328.0
26,2015-01-02 00:00:00,AA,3.0,JFK,LAX,-30.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,361.0
27,2015-01-03 00:00:00,AA,3.0,JFK,LAX,-14.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,369.0
28,2015-01-04 00:00:00,AA,3.0,JFK,LAX,-4.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,380.0
29,2015-01-05 00:00:00,AA,3.0,JFK,LAX,4.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,390.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201634,2015-01-11 00:00:00,NK,188.0,LAS,DTW,23.0,0.0,1749.0,0.0,0.0,0.0,23.0,0.0,269.0
201635,2015-01-12 00:00:00,NK,188.0,LAS,DTW,-9.0,0.0,1749.0,NaN,NaN,NaN,NaN,NaN,235.0
201636,2015-01-13 00:00:00,NK,188.0,LAS,DTW,68.0,0.0,1749.0,41.0,0.0,0.0,27.0,0.0,244.0
201637,2015-01-14 00:00:00,NK,188.0,LAS,DTW,-10.0,0.0,1749.0,NaN,NaN,NaN,NaN,NaN,237.0
201638,2015-01-02 00:00:00,NK,188.0,LGA,MYR,-14.0,0.0,563.0,NaN,NaN,NaN,NaN,NaN,116.0
201639,2015-01-03 00:00:00,NK,188.0,LGA,MYR,-14.0,0.0,563.0,NaN,NaN,NaN,NaN,NaN,121.0
201640,2015-01-04 00:00:00,NK,188.0,LGA,MYR,121.0,0.0,563.0,0.0,0.0,0.0,121.0,0.0,136.0
201641,2015-01-05 00:00:00,NK,188.0,LGA,MYR,87.0,0.0,563.0,0.0,0.0,0.0,87.0,0.0,129.0
201642,2015-01-06 00:00:00,NK,188.0,LGA,MYR,NaN,1.0,563.0,NaN,NaN,NaN,NaN,NaN,NaN
201643,2015-01-07 00:00:00,NK,188.0,LGA,MYR,NaN,1.0,563.0,NaN,NaN,NaN,NaN,NaN,NaN
201644,2015-01-08 00:00:00,NK,188.0,LGA,MYR,-13.0,0.0,563.0,NaN,NaN,NaN,NaN,NaN,110.0
201645,2015-01-09 00:00:00,NK,188.0,LGA,MYR,57.0,0.0,563.0,6.0,0.0,0.0,51.0,0.0,116.0
201646,2015-01-10 00:00:00,NK,188.0,LGA,MYR,85.0,0.0,563.0,0.0,0.0,74.0,11.0,0.0,103.0
201647,2015-01-11 00:00:00,NK,188.0,LGA,MYR,5.0,0.0,563.0,NaN,NaN,NaN,NaN,NaN,116.0
201648,2015-01-12 00:00:00,NK,188.0,LGA,MYR,NaN,1.0,563.0,NaN,NaN,NaN,NaN,NaN,NaN
201649,2015-01-13 00:00:00,NK,188.0,LGA,MYR,-7.0,0.0,563.0,NaN,NaN,NaN,NaN,NaN,134.0
201650,2015-01-14 00:00:00,NK,188.0,LGA,MYR,-3.0,0.0,563.0,NaN,NaN,NaN,NaN,NaN,127.0
201651,2015-01-02 00:00:00,NK,188.0,OAK,LAS,1.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,86.0
201652,2015-01-03 00:00:00,NK,188.0,OAK,LAS,-7.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,79.0
201653,2015-01-04 00:00:00,NK,188.0,OAK,LAS,-3.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,86.0
201654,2015-01-05 00:00:00,NK,188.0,OAK,LAS,-9.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,84.0
201655,2015-01-06 00:00:00,NK,188.0,OAK,LAS,5.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,90.0
201656,2015-01-07 00:00:00,NK,188.0,OAK,LAS,8.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,92.0
201657,2015-01-08 00:00:00,NK,188.0,OAK,LAS,-7.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,83.0
201658,2015-01-09 00:00:00,NK,188.0,OAK,LAS,-2.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,88.0
201659,2015-01-10 00:00:00,NK,188.0,OAK,LAS,-16.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,77.0
201660,2015-01-11 00:00:00,NK,188.0,OAK,LAS,-4.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,87.0
201661,2015-01-12 00:00:00,NK,188.0,OAK,LAS,-7.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,82.0
201662,2015-01-13 00:00:00,NK,188.0,OAK,LAS,23.0,0.0,407.0,3.0,0.0,0.0,20.0,0.0,103.0
201663,2015-01-14 00:00:00,NK,188.0,OAK,LAS,-7.0,0.0,407.0,NaN,NaN,NaN,NaN,NaN,82.0

In [3]:
#clean dataset by fill missing data with nan
clean_data_flight = data_flight.fillna(np.nan)
data_flight.head()

,flight_date,unique_carrier,flight_num,origin,dest,arr_delay,cancelled,distance,carrier_delay,weather_delay,late_aircraft_delay,nas_delay,security_delay,actual_elapsed_time
0,2015-01-02 00:00:00,AA,1.0,JFK,LAX,-19.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,381.0
1,2015-01-03 00:00:00,AA,1.0,JFK,LAX,-39.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,358.0
2,2015-01-04 00:00:00,AA,1.0,JFK,LAX,-12.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,385.0
3,2015-01-05 00:00:00,AA,1.0,JFK,LAX,-8.0,0.0,2475.0,NaN,NaN,NaN,NaN,NaN,389.0
4,2015-01-06 00:00:00,AA,1.0,JFK,LAX,25.0,0.0,2475.0,0.0,0.0,0.0,25.0,0.0,424.0

In [4]:
#sort data frame from arr_delay in descending order 
sort_data = clean_data_flight.sort_values("arr_delay", axis = 0, ascending = False, inplace = False, na_position ='last') 
sort_data.head()

,flight_date,unique_carrier,flight_num,origin,dest,arr_delay,cancelled,distance,carrier_delay,weather_delay,late_aircraft_delay,nas_delay,security_delay,actual_elapsed_time
11073,2015-01-11 00:00:00,AA,1595.0,AUS,DFW,1444.0,0.0,190.0,1444.0,0.0,0.0,0.0,0.0,59.0
10214,2015-01-13 00:00:00,AA,1487.0,OMA,DFW,1392.0,0.0,583.0,1392.0,0.0,0.0,0.0,0.0,117.0
12430,2015-01-03 00:00:00,AA,1677.0,MEM,DFW,1384.0,0.0,432.0,1380.0,0.0,0.0,4.0,0.0,104.0
8443,2015-01-04 00:00:00,AA,1279.0,OMA,DFW,1237.0,0.0,583.0,1222.0,0.0,15.0,0.0,0.0,102.0
10328,2015-01-05 00:00:00,AA,1495.0,EGE,DFW,1187.0,0.0,721.0,1019.0,0.0,168.0,0.0,0.0,127.0

In [5]:
# use lambda function to sort occuring (flight_delay) that records True or False 
data_flight_delay = sort_data ["arr_delay"].apply(lambda f: f >0)
print(data_flight_delay)

11073      True
10214      True
12430      True
8443       True
10328      True
36570      True
36495      True
59072      True
32173      True
56488      True
52441      True
53864      True
14745      True
53863      True
35702      True
13209      True
129594     True
44319      True
827        True
34627      True
115065     True
8785       True
3286       True
11226      True
139064     True
14750      True
186113     True
111959     True
36249      True
190694     True
          ...
200947    False
200948    False
200955    False
200956    False
200957    False
200966    False
201001    False
201010    False
201022    False
201023    False
201027    False
201069    False
201126    False
201306    False
201320    False
201321    False
201323    False
201329    False
201330    False
201332    False
201339    False
201412    False
201444    False
201476    False
201526    False
201554    False
201594    False
201642    False
201643    False
201648    False
Name: arr_delay, Length: 201664, dtype: bool

In [6]:
#use value count to sort aggregate trends of flight_delay
count_sort_data = data_flight_delay. value_counts()
print(count_sort_data)

False    103037
True      98627
Name: arr_delay, dtype: int64

In [7]:
#count total percentage of flight_delay
flight_not_delayed = data_flight_delay .value_counts()[0]
data_flight_delayed = data_flight_delay .value_counts()[1]
total_sum_flight = flight_not_delayed + data_flight_delayed
#calculate %
print (float (data_flight_delayed)/total_sum_flight)

0.4890659711202793

In [10]:
#calculate numbers of fight_delay longer than 20 minutes
sort_data ['longer_than_20mins'] = sort_data ["arr_delay"]. apply(lambda f: f >20)
count_delay_20mins = sort_data ['longer_than_20mins'].value_counts()
print(count_delay_20mins)

False    152985
True      48679
Name: longer_than_20mins, dtype: int64